fix cvar generation python script
Summary:
use `strip` instead of `trim` to trim spaces in a string.

Previous error: `AttributeError: 'str' object has no attribute 'trim'. Did you mean: 'strip'?`

Reviewed By: cenzhaometa

Differential Revision: D51830553

fbshipit-source-id: 215e05aba3413a7d89cd98f3f98719c8a963a248